# Generated by Django 6.0.5 on 2026-05-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI兼容"), ("custom", "自定义")],
                        default="openai",
                        max_length=20,
                        verbose_name="提供商",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                ("api_url", models.CharField(max_length=255, verbose_name="API地址")),
                (
                    "model_name",
                    models.CharField(
                        default="mimo-v2.5-pro", max_length=100, verbose_name="模型名称"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户AI配置",
                "verbose_name_plural": "用户AI配置",
            },
        ),
    ]
