# Generated by Django 6.0.5 on 2026-05-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="试卷标题")),
                ("total_score", models.IntegerField(default=0, verbose_name="总分")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待完成"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "试卷",
                "verbose_name_plural": "试卷",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="序号")),
                ("score", models.IntegerField(default=10, verbose_name="分值")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField(verbose_name="用户答案")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确"),
                ),
                ("score", models.IntegerField(default=0, verbose_name="得分")),
                ("ai_feedback", models.TextField(blank=True, verbose_name="AI反馈")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="答题时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_answers",
                        to="questions.question",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "答题记录",
                "verbose_name_plural": "答题记录",
            },
        ),
    ]
