# Generated by Django 6.0.5 on 2026-05-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "题目分类",
                "verbose_name_plural": "题目分类",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("choice", "选择题"),
                            ("fill", "填空题"),
                            ("code", "编程题"),
                            ("short", "简答题"),
                        ],
                        max_length=10,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="难度",
                    ),
                ),
                ("content", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="选项（选择题）"
                    ),
                ),
                ("answer", models.TextField(verbose_name="正确答案")),
                ("explanation", models.TextField(blank=True, verbose_name="答案解析")),
                (
                    "created_by_ai",
                    models.BooleanField(default=False, verbose_name="AI生成"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "ordering": ["-created_at"],
            },
        ),
    ]
