# Generated by Django 5.2.1 on 2026-05-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_question_user_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="题库名"),
        ),
        migrations.AddField(
            model_name="question",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="已上线"),
        ),
    ]
