# Generated by Django 6.0.5 on 2026-05-12 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_type",
                    models.CharField(
                        choices=[("generate", "生成题目"), ("evaluate", "评判答案")],
                        max_length=20,
                        verbose_name="API类型",
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, verbose_name="输入Token"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, verbose_name="输出Token"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="总Token"),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="mimo-v2.5-pro", max_length=50, verbose_name="模型名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="调用时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token消耗记录",
                "verbose_name_plural": "Token消耗记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
